server:
  servlet:
    context-path: /api

spring:
  application:
    name: marketplace-api
  datasource:
    url: jdbc:postgresql://localhost:5432/marketplace
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
      database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  servlet:
    multipart:
      max-file-size: 10MB

  # Configurações de segurança
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: spring-boot-client
            client-secret: 5wsr3ckGoPdle9VHM995gurle5J4w0Sz
            scope: openid, profile, email
            redirect-uri: http://localhost:8080/login/oauth2/code/keycloak
            # redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
        provider:
          keycloak:
            issuer-uri: http://localhost:8280/realms/marketplace
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8280/realms/marketplace
keycloak:
  auth-server-url: http://localhost:8280
  realm: marketplace
  resource: spring-boot-client
  public-client: false
  credentials:
    secret: 5wsr3ckGoPdle9VHM995gurle5J4w0Sz
    ssl-required: external
    bearer-only: true
    use-resource-role-mappings: true

# Configurações de logging
logging:
  level:
    org:
      flywaydb: debug
      hibernate:
        type.descriptor.sql: trace
      springframework:
        web:
        filter: info
        client: debug
        transaction: error
        api.lojaapi: debug
      security:
        org.springframework.security: DEBUG
        com.br.core.configuracoes.WebSecurityConfig: DEBUG

# Configurações do Swagger + OpenAPI

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui

openapi:
  title: API do MARKETPLACE
  description: Documentação OpenApi v3 da API do MARKETPLACE
  version: 1.0.0
  contact:
    name: guest
    url: https://example.com
    email: guest@gmail.com
  base-url: http://localhost:8080/api
